export interface LanguageStrings {
  search: string;
  getSearchPlaceholder: string;
  home: string;
  tvShows: string;
  movies: string;
  trending: string;
  myList: string;
  gptSearch: string;
  play: string;
  moreInfo: string;
  nowPlaying: string;
  popular: string;
  topRated: string;
  upcoming: string;
  recommendationsForYou: string;
  watchlistEmpty: string;
  addedToWatchlist: string;
  removedFromWatchlist: string;
  signIn: string;
  signUp: string;
  signOut: string;
  guestLogin: string;
  or: string;
  emailPlaceholder: string;
  passwordPlaceholder: string;
  namePlaceholder: string;
  newToNetflix: string;
  alreadyRegistered: string;
  signUpNow: string;
  signInNow: string;
  matchScore: string;
  cast: string;
  genres: string;
  whereToWatch: string;
  aiThinking: string;
  aiSuggestedPrompt: string;
  tryThese: string;
  close: string;
  watchTrailer: string;
  releaseDate: string;
  duration: string;
  min: string;
}

export const language: Record<string, LanguageStrings> = {
    en: {
        search: "Search",
        getSearchPlaceholder: "What would you like to watch today? e.g. Cyberpunk detective thriller",
        home: "Home",
        tvShows: "TV Shows",
        movies: "Movies",
        trending: "Trending Now",
        myList: "My List",
        gptSearch: "AI Movie Assistant",
        play: "Play",
        moreInfo: "More Info",
        nowPlaying: "Now Playing in Theatres",
        popular: "Popular on Netflix",
        topRated: "Top Rated Blockbusters",
        upcoming: "Upcoming Releases",
        recommendationsForYou: "AI Curated For You",
        watchlistEmpty: "Your watchlist is empty. Explore movies and click + to add them here!",
        addedToWatchlist: "Added to your Watchlist",
        removedFromWatchlist: "Removed from your Watchlist",
        signIn: "Sign In",
        signUp: "Sign Up",
        signOut: "Sign Out",
        guestLogin: "Quick Guest Sign-In (Demo)",
        or: "OR",
        emailPlaceholder: "Email address",
        passwordPlaceholder: "Password",
        namePlaceholder: "Full Name",
        newToNetflix: "New to Netflix?",
        alreadyRegistered: "Already registered?",
        signUpNow: "Sign up now.",
        signInNow: "Sign in now.",
        matchScore: "Match",
        cast: "Top Cast",
        genres: "Genres",
        whereToWatch: "Available On",
        aiThinking: "Gemini AI is crafting personalized movie suggestions...",
        aiSuggestedPrompt: "Suggested AI Prompts",
        tryThese: "Try asking:",
        close: "Close",
        watchTrailer: "Watch Trailer",
        releaseDate: "Release Date",
        duration: "Runtime",
        min: "min",
    },
    hindi: {
        search: "खोजें",
        getSearchPlaceholder: "आज आप क्या देखना चाहेंगे? जैसे: रहस्य रोमांचक फिल्में",
        home: "होम",
        tvShows: "टीवी शो",
        movies: "फ़िल्में",
        trending: "ट्रेंडिंग",
        myList: "मेरी सूची",
        gptSearch: "AI मूवी सहायक",
        play: "चलाएँ",
        moreInfo: "अधिक जानकारी",
        nowPlaying: "सिनेमाघरों में",
        popular: "नेटफ्लिक्स पर लोकप्रिय",
        topRated: "सर्वोच्च रेटेड फ़िल्में",
        upcoming: "आने वाली फ़िल्में",
        recommendationsForYou: "आपके लिए AI सुझाव",
        watchlistEmpty: "आपकी सूची खाली है। फ़िल्में ब्राउज़ करें और + पर क्लिक करें!",
        addedToWatchlist: "आपकी सूची में जोड़ा गया",
        removedFromWatchlist: "आपकी सूची से हटाया गया",
        signIn: "साइन इन करें",
        signUp: "साइन अप करें",
        signOut: "साइन आउट",
        guestLogin: "त्वरित अतिथि साइन-इन (डेमो)",
        or: "या",
        emailPlaceholder: "ईमेल पता",
        passwordPlaceholder: "पासवर्ड",
        namePlaceholder: "पूरा नाम",
        newToNetflix: "नेटफ्लिक्स पर नए हैं?",
        alreadyRegistered: "पहले से पंजीकृत हैं?",
        signUpNow: "अभी साइन अप करें।",
        signInNow: "अभी साइन इन करें।",
        matchScore: "मैच",
        cast: "मुख्य कलाकार",
        genres: "शैलियाँ",
        whereToWatch: "यहाँ उपलब्ध है",
        aiThinking: "Gemini AI आपके लिए सर्वोत्तम फ़िल्में खोज रहा है...",
        aiSuggestedPrompt: "सुझाए गए AI संकेत",
        tryThese: "पूछकर देखें:",
        close: "बंद करें",
        watchTrailer: "ट्रेलर देखें",
        releaseDate: "रिलीज़ की तारीख",
        duration: "अवधि",
        min: "मिनट",
    },
    spanish: {
        search: "Buscar",
        getSearchPlaceholder: "¿Qué te gustaría ver hoy? ej. Suspense de ciencia ficción",
        home: "Inicio",
        tvShows: "Series",
        movies: "Películas",
        trending: "Tendencias",
        myList: "Mi Lista",
        gptSearch: "Asistente IA",
        play: "Reproducir",
        moreInfo: "Más información",
        nowPlaying: "En Cines Ahora",
        popular: "Popular en Netflix",
        topRated: "Más Valoradas",
        upcoming: "Próximos Estrenos",
        recommendationsForYou: "Recomendado por IA",
        watchlistEmpty: "Tu lista está vacía. ¡Explora películas y haz clic en + para agregarlas!",
        addedToWatchlist: "Añadido a Mi Lista",
        removedFromWatchlist: "Eliminado de Mi Lista",
        signIn: "Iniciar sesión",
        signUp: "Registrarse",
        signOut: "Cerrar sesión",
        guestLogin: "Acceso de invitado rápido (Demo)",
        or: "O",
        emailPlaceholder: "Correo electrónico",
        passwordPlaceholder: "Contraseña",
        namePlaceholder: "Nombre completo",
        newToNetflix: "¿Primera vez en Netflix?",
        alreadyRegistered: "¿Ya tienes cuenta?",
        signUpNow: "Suscríbete ya.",
        signInNow: "Inicia sesión ya.",
        matchScore: "de coincidencia",
        cast: "Reparto principal",
        genres: "Géneros",
        whereToWatch: "Disponible en",
        aiThinking: "Gemini AI está buscando recomendaciones personalizadas...",
        aiSuggestedPrompt: "Sugerencias de IA",
        tryThese: "Prueba preguntar:",
        close: "Cerrar",
        watchTrailer: "Ver Tráiler",
        releaseDate: "Fecha de estreno",
        duration: "Duración",
        min: "min",
    },
    french: {
        search: "Rechercher",
        getSearchPlaceholder: "Que voulez-vous regarder aujourd'hui ? ex. Thriller futuriste",
        home: "Accueil",
        tvShows: "Séries",
        movies: "Films",
        trending: "Tendances actuelles",
        myList: "Ma Liste",
        gptSearch: "Assistant IA",
        play: "Lecture",
        moreInfo: "Plus d'infos",
        nowPlaying: "Actuellement au cinéma",
        popular: "Populaire sur Netflix",
        topRated: "Les Mieux Notés",
        upcoming: "Prochainement",
        recommendationsForYou: "Suggestions IA pour vous",
        watchlistEmpty: "Votre liste est vide. Explorez les films et cliquez sur + pour les ajouter !",
        addedToWatchlist: "Ajouté à votre liste",
        removedFromWatchlist: "Retiré de votre liste",
        signIn: "S'identifier",
        signUp: "S'inscrire",
        signOut: "Se déconnecter",
        guestLogin: "Connexion invité rapide (Démo)",
        or: "OU",
        emailPlaceholder: "Adresse e-mail",
        passwordPlaceholder: "Mot de passe",
        namePlaceholder: "Nom complet",
        newToNetflix: "Nouveau sur Netflix ?",
        alreadyRegistered: "Déjà inscrit ?",
        signUpNow: "Inscrivez-vous.",
        signInNow: "Identifiez-vous.",
        matchScore: "Recommandé à",
        cast: "Distribution",
        genres: "Genres",
        whereToWatch: "Disponible sur",
        aiThinking: "Gemini IA prépare vos recommandations sur mesure...",
        aiSuggestedPrompt: "Suggestions IA",
        tryThese: "Essayez :",
        close: "Fermer",
        watchTrailer: "Voir la bande-annonce",
        releaseDate: "Date de sortie",
        duration: "Durée",
        min: "min",
    },
    german: {
        search: "Suchen",
        getSearchPlaceholder: "Was möchtest du heute sehen? z.B. Sci-Fi Thriller",
        home: "Startseite",
        tvShows: "Serien",
        movies: "Filme",
        trending: "Angesagt",
        myList: "Meine Liste",
        gptSearch: "KI Filmassistent",
        play: "Abspielen",
        moreInfo: "Weitere Infos",
        nowPlaying: "Neu im Kino",
        popular: "Beliebt auf Netflix",
        topRated: "Top-Bewertungen",
        upcoming: "Demnächst",
        recommendationsForYou: "KI-Empfehlungen für dich",
        watchlistEmpty: "Deine Liste ist leer. Durchstöbere Filme und klicke auf +!",
        addedToWatchlist: "Zu meiner Liste hinzugefügt",
        removedFromWatchlist: "Aus meiner Liste entfernt",
        signIn: "Einloggen",
        signUp: "Registrieren",
        signOut: "Ausloggen",
        guestLogin: "Schneller Gast-Zugang (Demo)",
        or: "ODER",
        emailPlaceholder: "E-Mail-Adresse",
        passwordPlaceholder: "Passwort",
        namePlaceholder: "Vollständiger Name",
        newToNetflix: "Neu bei Netflix?",
        alreadyRegistered: "Bereits registriert?",
        signUpNow: "Jetzt registrieren.",
        signInNow: "Jetzt einloggen.",
        matchScore: "Übereinstimmung",
        cast: "Besetzung",
        genres: "Genres",
        whereToWatch: "Verfügbar auf",
        aiThinking: "Gemini KI generiert persönliche Filmempfehlungen...",
        aiSuggestedPrompt: "Vorgeschlagene KI-Prompts",
        tryThese: "Versuche:",
        close: "Schließen",
        watchTrailer: "Trailer ansehen",
        releaseDate: "Erscheinungsdatum",
        duration: "Laufzeit",
        min: "Min.",
    },
    japanese: {
        search: "検索",
        getSearchPlaceholder: "今日は何を観たいですか？ 例：SFサスペンス傑作",
        home: "ホーム",
        tvShows: "テレビ番組",
        movies: "映画",
        trending: "急上昇",
        myList: "マイリスト",
        gptSearch: "AI映画アシスタント",
        play: "再生",
        moreInfo: "詳細情報",
        nowPlaying: "劇場公開中",
        popular: "Netflixで人気",
        topRated: "高評価作品",
        upcoming: "近日公開",
        recommendationsForYou: "AIによるおすすめ",
        watchlistEmpty: "マイリストは空です。映画を見つけて＋で追加しましょう！",
        addedToWatchlist: "マイリストに追加しました",
        removedFromWatchlist: "マイリストから削除しました",
        signIn: "ログイン",
        signUp: "新規登録",
        signOut: "ログアウト",
        guestLogin: "クイックゲストログイン (デモ)",
        or: "または",
        emailPlaceholder: "メールアドレス",
        passwordPlaceholder: "パスワード",
        namePlaceholder: "お名前",
        newToNetflix: "Netflixを初めてご利用ですか？",
        alreadyRegistered: "すでにアカウントをお持ちですか？",
        signUpNow: "今すぐ登録。",
        signInNow: "今すぐログイン。",
        matchScore: "マッチ",
        cast: "キャスト",
        genres: "ジャンル",
        whereToWatch: "配信サービス",
        aiThinking: "Gemini AIがパーソナライズされた映画を検索中...",
        aiSuggestedPrompt: "おすすめAIプロンプト",
        tryThese: "おすすめの質問：",
        close: "閉じる",
        watchTrailer: "予告編を見る",
        releaseDate: "公開日",
        duration: "再生時間",
        min: "分",
    },
};
